In [15]:
import numpy as np

def maxpool(n, A):
  result = np.zeros((int(n/2), int(n/2)))
  
  for idx1 in range(int(n/2)):
    i = idx1*2
    for idx2 in range(int(n/2)):
      j = idx2*2
      result[idx1, idx2] = np.max(A[i:i+2, j:j+2])
    
  return result
    

print("Input:")
n = int(input())

A = np.random.random((n, n))
print("\nOutput:")
print(A)

B = maxpool(n, A)
print(B)

Input:
4

Output:
[[0.67424887 0.65758154 0.99037709 0.44772359]
 [0.59272923 0.96229001 0.62174407 0.04287602]
 [0.56958929 0.99846668 0.54455657 0.31541148]
 [0.63795117 0.85933752 0.57776809 0.92486126]]
[[0.96229001 0.99037709]
 [0.99846668 0.92486126]]
